### ISSUE TITLE
[Give Up Robot] auto splitter does not [split properly]

### ISSUE THREAD

**Issue by rtdrtd67** [just-ero/asl#10]
Please refer to the [common issues](https://github.com/just-ero/asl#issues) before creating an issue.

---

## *Describe your Issue*

Give Up Robot.exe Autosplitter:

If there is any especially weird behavior with the timer, please describe what is happening:  

On level transitions, when it's just supposed to split, it sometimes resets the timer as well, instead of just splitting. This causes fake golds, such as when completing level 1, the timer will split and reset the time back to 0.00, causing livesplit to think I just completed level 1 in 0 seconds.

**Comment by ero-qt** [comment]
Do you think you could give it a try now?

**Comment by rtdrtd67** [comment]
just did two quick playthroughs and it's working perfectly, will notify if any issues come up later on.
