### ISSUE TITLE
Commission for Hello Neighbor 2

### ISSUE THREAD

**Issue by KKuehlem** [just-ero/asl#12]
For rates and other information, please refer to my commission info [here](https://github.com/just-ero/asl#commissions).  
- [X] I have read and understood these terms.

## *Auto Splitter Commission*
* Game name: Hello Neighbor 2
* Download/store link (+ price if applicable): $40 on steam: https://store.steampowered.com/app/1321680/Hello_Neighbor_2/

*Features*:  
- [ ] Start: Describe an event or events upon which the timer should start.  
- [ ] Split: Describe an event or events upon which the timer should split.  
- [ ] Reset: Describe an event or events upon which the timer should reset.  
- [X] Load removal / game time synchronization: Explain how your game's in-game time works. If not applicable, please explain when and how loading times should be removed.

I want the timer to pause during loading. The rule in speedrun.com have the following definition for the loading:
"Loading starts when the loading van appears Loading ends the first frame that gameplay is visible in the background whilst the van is fading out. The gameplay will be slightly visible."
Loading times in Hello Neighbor 2 are extremely influenced by the hardware and might not even be consistent between runs on the same machine.

**Comment by ero-qt** [comment]
According to this screenshot from the speedrun tool development server, an auto splitter has already been completed. Is this accurate?
![image](https://user-images.githubusercontent.com/56401411/209887029-f1f6f4b5-beca-4b35-8f10-0de087d302bd.png)

**Comment by KKuehlem** [comment]
Yes, seems like it, thank you. Do you mind sharing me the link for this discord server?

**Comment by ero-qt** [comment]
Here's an invite to the speedrun tool development server: https://discord.gg/N6wv8pW  
And one to the Hello Neighbor speedrunning server, in case you're not in that one yet: https://discord.gg/hvAbaeC

**Comment by KKuehlem** [comment]
I asked in the discord and Hawkz but as it seems they don't have that load remover anymore (I don't know why). So if you would like to make one it would be very much appreciated

**Comment by ero-qt** [comment]
I'm pretty busy with other work, I don't think I'll be able to take this one on, I'm sorry.

**Comment by KKuehlem** [comment]
Ok, thanks anyway
