### ISSUE TITLE
[Cuphead] Autosplitter does not split correctly on legacy patches

### ISSUE THREAD

**Issue by mitchell-merry** [just-ero/asl#2]
## *Describe your Issue*
The autosplitter does not split for legacy patches (i.e. 1.0, 1.1.5, 1.2.4) on boss / run 'n gun completion. These need to be supported.

It does however:
- Start time
- Pause for loads
- Split correctly at splits tagged with:
  - (Enter Scene)
  - (Level)
  - (Super)
  - King Dice Contract Cutscene is untested

Does not split at splits tagged with (Boss) or (Run 'n Gun).

Enter Level (IL) and End Level (IL) also do not work, on any patch (so including the otherwise-working 1.3.2 DLC patch), so I'll create another issue after this one with details on that.

NOTE that this is not comprehensively tested for all versions and for all splits, just my own observations on certain types of splits.

## *Causes and Fixes*
Doing some logging here (line 85):
![image](https://user-images.githubusercontent.com/8567231/178496705-01b923c0-04ca-4bb8-8a6f-451564efe0a9.png)

Results in the following logs for 1.2.4 (ignore the final line with False, that is unrelated):
![image](https://user-images.githubusercontent.com/8567231/178496849-7373a64c-6c6b-4605-975e-3525f525072b.png)
(PlayerLevelDataObject pointers being read as 8 bytes instead of 4 - only one that appears to work is the last one since it has nothing next to it). Following the 4 byte pointers manually correctly takes me to the PlayerLevelDataObjects.

Whereas for 1.3.2 with DLC:
![image](https://user-images.githubusercontent.com/8567231/178498183-8fb2d99c-f458-4483-845e-6b5b4226dbf2.png)
(Still being read as 8 bytes, but that is correct this time as the pointers are actually 8 bytes)

The offsets logged are correct in both cases.

I think this might be an issue with the ASLHelper library itself. I'm not sure a) why these are 32 bit instead of 64 bit or b) why it changed with the new patch.

## Changing Versions / Multi-Install
(I'm assuming wolf gifted you the base game and the DLC, I don't actually know if you own the DLC)

If you want to test the various versions, here's how you do it; there are 5 different versions of the game that need to be supported, namely:
- 1.0 (referred to as Legacy on speedrun.com)
- 1.1.5
- 1.2.4
- 1.3.2 without DLC (Relatively untested but *probably* working, I need to reinstall this)
- 1.3.2 with DLC (Working other than the enter/end level issue mentioned earlier)

You can up/down patch using the Betas section of the game's properties on Steam. Doing so can sometimes cause 3gb downloads, so...

I have all five versions installed simultaneously, you can follow this guide: https://www.speedrun.com/cuphead/guide/4uzgw to replicate my setup, if you need to.

To install 1.3.2 without DLC, have 1.3.2 currently installed and then untick the DLC box here:
![image](https://user-images.githubusercontent.com/8567231/178500982-94ce5e03-b2b8-4c43-9282-058e9e89f28b.png)

Thanks a bunch! Let me know if you need anymore details on this

**Comment by ero-qt** [comment]
This is a temporary fix to bridge the time where DevilSquirrel cannot fix their component. It is not meant to fully replace it.

**Comment by mitchell-merry** [comment]
It's unlikely DevilSquirrel will have time to work on the existing component anytime soon, so we might go a long time without getting an update (I will probably have to do it myself if we want to retain the original current UI, but who knows how long that could take)

This also might be a bug with the ASLHelper library itself, so it extends to more than just the Cuphead ASL



This fix also means if people want to run the older patches now (the only leaderboards actually on speedrun.com atm) they need to manually install the original component themselves

**Comment by ero-qt** [comment]
Please give it a go now.

**Comment by mitchell-merry** [comment]
This seems to have been resolved! Confirmed working on all versions. Thanks a lot for your quick work in getting this ASL setup and resolving these issues! The community is very thankful.
